<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data_Layer\Data_Layer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Middlewares\" />
    <Folder Include="Repository\Payment\" />
    <Folder Include="Services\Api\" />
    <Folder Include="Services\ImageServices\" />
    <Folder Include="Services\TextServices\" />
    <Folder Include="Services\Persian\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Azure.Core" Version="1.47.1" />
 
  </ItemGroup>

</Project>
